### ISSUE TITLE
API calls don't return same as curl

### ISSUE THREAD

**Issue by curtsheller** [getsendstack/laravel-sendstack#6]
email is '**Unsubscribed**' on SendStack Subscribers panel.

![image](https://user-images.githubusercontent.com/43849/200125905-1ec17ddb-8244-4fca-a220-00f19dab04bc.png)

Call to API:

```
$newsletter = SendStack::subscribers()->get(
            query: 'yogibear@curtsheller.com, // This can be either the subscribers UUID or their Email Address
        );
```
Returns status: SUBSCRIBED.

![image](https://user-images.githubusercontent.com/43849/200125894-725a478a-0c26-46f3-ab67-8f45a5d9ef73.png)

curl command GET /api/subscribers/{UUID} does return the right status:

![image](https://user-images.githubusercontent.com/43849/200126006-b29f9f22-9f82-4ebf-a91a-596a82e76336.png)

**Comment by alexgaal** [comment]
I cannot verify this issue. I just triggered a call and it returned:

```
>>> SendStack::subscribers()->get('mario.*****@******.at')
=> SendStack\Laravel\DataObjects\Subscriber {#4944
     +uuid: "d6c1ddce-b6b1-4f93-a54b-6fcce467b831",
     +email: "mario.*****@******.at",
     +name: SendStack\Laravel\DataObjects\Name {#4919
       +first: "Mario",
       +last: "*****",
     },
     +meta: "",
     +tags: [],
     +status: SendStack\Laravel\Enums\Status {#4942
       +name: "PENDING",
       +value: "pending",
     },
     +confirmed: Illuminate\Support\Carbon @1667663215 {#4950
       date: 2022-11-05 15:46:55.765122 UTC (+00:00),
     },
     +unsubscribed: Illuminate\Support\Carbon @1667663215 {#4978
       date: 2022-11-05 15:46:55.765208 UTC (+00:00),
     },
   }
   ```

**Comment by alexgaal** [comment]
I cannot verify this issue. I just triggered a call and it returned:

>>> SendStack::subscribers()->get('mario.*****@******.at')
=> SendStack\Laravel\DataObjects\Subscriber {#4944
     +uuid: "********-b6b1-4f93-a54b-6fcce467b831",
     +email: "mario.*****@******.at",
     +name: SendStack\Laravel\DataObjects\Name {#4919
       +first: "Mario",
       +last: "*****",
     },
     +meta: "",
     +tags: [],
     +status: SendStack\Laravel\Enums\Status {#4942
       +name: "PENDING",
       +value: "pending",
     },
     +confirmed: Illuminate\Support\Carbon @1667663215 {#4950
       date: 2022-11-05 15:46:55.765122 UTC (+00:00),
     },
     +unsubscribed: Illuminate\Support\Carbon @1667663215 {#4978
       date: 2022-11-05 15:46:55.765208 UTC (+00:00),
     },
   }

**Comment by mpociot** [comment]
This is now fixed!
