### ISSUE TITLE
Update Request does not update subscription status

### ISSUE THREAD

**Issue by alexanderkroneis** [getsendstack/laravel-sendstack#7]
Hi,

I implemented a `SubscribeNewsletterAction` which takes `bool $optIn` to opt-in and opt-out from the newsletter. This is my action:

```php
public function execute(User $user, bool $optIn = false): bool
{
    $subscriberRequest = new SubscriberRequest(
        email: $user->email,
        firstName: $user->first_name,
        lastName: $user->last_name,
        optIn: $optIn,
    );

    try {
        if (SendStack::isActiveSubscriber($user->email)) {
            $subscriber = SendStack::subscribers()->get(
                query: $user->email
            );

            SendStack::subscribers()->update(
                $subscriber->uuid,
                $subscriberRequest,
            );
        }

        SendStack::subscribers()->create(
            $subscriberRequest
        );
    } catch (SendStackApiException $exception) {
        return false;
    }

    return true;
}
```

When I call `$action->execute($user, false)` it does not update the subscription state of the specific user.

<img width="626" alt="image" src="https://user-images.githubusercontent.com/12985989/200129518-68ae482e-3923-4865-8c5b-ea8b135754df.png">

**Comment by JustSteveKing** [comment]
@mpociot could you confirm this one please? As far as the package goes this **should** work

**Comment by alexanderkroneis** [comment]
Any updates? @mpociot

**Comment by mpociot** [comment]
If you want to unsubscribe a user, you should make a DELETE request.
The `optIn` field is only used to identify whether or not you already have obtained an opt-in for the given subscriber. Otherwise SendStack will send out a opt-in mail again.

**Comment by alexanderkroneis** [comment]
I talked to @mpociot. `$optIn` should be an indicator whether the user already gave the permission to send emails. `$optIn = false` would mean, that they don't want to be contacted. In my case a deletion of a subscriber would be correct behavior.
